{{- if .Values.authelia.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ printf "%s-authelia" .Release.Name }}
  namespace: {{ $.Release.Namespace | quote }}
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: 'true'
spec:
  encryptedData:
    authelia_jwt_secret_file: {{ .Values.authelia.secrets.jwtSecret }}
    authelia_storage_encryption_key_file: {{ .Values.authelia.secrets.storageEncryptionKey }}
    authelia_authentication_backend_ldap_password_file: {{ .Values.authelia.secrets.backendLdapPassword }}
    authelia_identity_providers_oidc_issuer_private_key_file: {{ .Values.authelia.secrets.issuer }}
    authelia_identity_providers_oidc_hmac_secret_file: {{ .Values.authelia.secrets.hmac }}
    {{- if .Values.authelia.secrets.redis }}
    authelia_session_redis_password_secret_file: {{ .Values.authelia.secrets.redis }}
    {{- end }}
    {{- if .Values.authelia.secrets.session }}
    authelia_session_secret_file: {{ .Values.authelia.secrets.session }}
    {{- end }}
  template:
    type: Opaque
{{- end }}
