{{- if .Values.ingress.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-ingress" .Release.Name }}
  namespace: ingress
  annotations:
    metallb.universe.tf/allow-shared-ip: {{ tpl .Values.ingress.loadBalancerIpAddress . }}
spec:
  selector:
    {{ .Values.ingress.selector }} 
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
  type: LoadBalancer
  loadBalancerIP: {{ tpl .Values.ingress.loadBalancerIpAddress . }}
{{- end }}
