{{ if .Values.squid.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-squid" .Release.Name }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    metallb.universe.tf/allow-shared-ip: {{ tpl .Values.squid.loadBalancerIpAddress . }}
    service.kubernetes.io/topology-aware-hints: auto
spec:
  type: LoadBalancer
  loadBalancerIP: {{ tpl .Values.squid.loadBalancerIpAddress . }}
  externalTrafficPolicy: {{ .Values.squid.externalTrafficPolicy | quote }}
  ports:
    - name: proxy
      protocol: TCP
      port: {{ .Values.squid.squidPort }}
      targetPort: 3128
  selector:
    app: squid
{{- end }}
