apiVersion: v2
name: idmz
version: "0.0.28"
description: Helm chart for common IDMZ applications.
type: application
keywords:
  - idmz
  - dmz
home: https://github.com/cybertrol-engineering/idmz-helm
sources:
  - https://github.com/cybertrol-engineering/idmz-helm
maintainers:
  - name: alphabet5
    url: https://github.com/alphabet5
  - name: cybertrol-engineering
    url: https://github.com/cybertrol-engineering
deprecated: false
